config/routes.rb
Rails.application.routes.draw do
  resources :crimes

  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root "crimes#index"

end

app/models/crime.rb
class Crime < ActiveRecord::Base
	has_attached_file :image, styles: { :medium => "300x300>"}
	has_attached_file :video
	
 	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController
  before_action :set_crime, only: [:show, :edit, :update, :destroy]

  # GET /crimes
  # GET /crimes.json
  def index
    @crimes = Crime.all
  end

  # GET /crimes/1
  # GET /crimes/1.json
  def show
  end

  # GET /crimes/new
  def new
    @crime = Crime.new
  end

  # GET /crimes/1/edit
  def edit
  end

  def locations
    crimes= Crime.all
    cr=[]
    crl=Hash.new
    crimes.each do |c|
      cr.inject(c.Location)
    end
    print "##############################################################"
    print "##############################################################"
    print "##############################################################"
    print "##############################################################"
    print cr
    print "##############################################################"
    print "##############################################################"
    print "##############################################################"
    print "##############################################################"
  end

  # POST /crimes
  # POST /crimes.json
  def create
    @crime = Crime.new(crime_params)
    @user = current_user



    respond_to do |format|
      if @crime.save
        format.html { redirect_to @crime, notice: 'Crime was successfully uploaded.' }
        format.json { render :show, status: :created, location: @crime }
        #UserMailer.sample_email(@user,@crime).deliver
      else
        format.html { render :new }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crimes/1
  # PATCH/PUT /crimes/1.json
  def update
    respond_to do |format|
      if @crime.update(crime_params)
        format.html { redirect_to @crime, notice: 'Crime was successfully updated.' }
        format.json { render :show, status: :ok, location: @crime }
      else
        format.html { render :edit }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crimes/1
  # DELETE /crimes/1.json
  def destroy
    @crime.destroy
    respond_to do |format|
      format.html { redirect_to crimes_url, notice: 'Crime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crime
      @crime = Crime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crime_params
      params.require(:crime).permit(:Name, :Location, :Description, :Ctime, :Attachment, :image, :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/views/crimes/_form.html.erb
<%= form_for(@crime) do |f| %>
  <% if @crime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crime.errors.count, "error") %> prohibited this crime from being saved:</h2>

      <ul>
      <% @crime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Location %><br>
    <%= f.text_field :Location %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :Ctime %><br>
    <%= f.datetime_select :Ctime %>
  </div>
  <div class="field">
    <%= f.label :Attachment %><br>
    <%= f.check_box :Attachment %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
    <div class="field">
    <%= f.file_field :video %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crimes/edit.html.erb
<h1>Editing crime</h1>

<%= render 'form' %>

<%= link_to 'Show', @crime %> |
<%= link_to 'Back', crimes_path %>

app/views/crimes/index.html.erb
<% if current_user.try(:admin?) %>

<h1>Listing crimes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Description</th>
      <th>Ctime</th>
      <th>Attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crimes.each do |crime| %>
      <tr>
        <td><%= crime.Name %></td>
        <td><%= crime.Location %></td>
        <td><%= crime.Description %></td>
        <td><%= crime.Ctime %></td>
        <td><%= crime.Attachment %></td>
        <td><%= link_to 'Show', crime %></td>
        <td><%= link_to 'Edit', edit_crime_path(crime) %></td>
        <td><%= link_to 'Destroy', crime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

<%= link_to 'New Crime', new_crime_path %>

app/views/crimes/new.html.erb
<h1>New crime</h1>

<%= render 'form' %>

<%= link_to 'Back', crimes_path %>

app/views/crimes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crime.Name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @crime.Location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @crime.Description %>
</p>

<p>
  <strong>Ctime:</strong>
  <%= @crime.Ctime %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= @crime.Attachment %>
</p>

<p>
  <%= image_tag @crime.image.url(:medium) %>
</p>

<% if @crime.video? %>
<h1 class="center">
<%= @crime.Name %>
</h1><br />
<%= video_path @crime.video.url %>       
<% end %>
<video width="490" height="275" src="<%= video_path @crime.video.url %>" frameborder="0" allowfullscreen autoplay="true">
            </video>

<%= link_to 'Edit', edit_crime_path(@crime) %>

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Crime Upload
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-inverse
		.container
			.navbar-brand= link_to "Crime Upload", root_path

			%ul.nav.navbar-nav.navbar-right
				%li= link_to "Add a Crime", new_crime_path
				%li= link_to "Sign in", new_user_session_path
				%li= link_to "Sign out", destroy_user_session_path, method: :delete


	.containerd
		= yield